WidgetMetadata = {
  id: "rou",
  title: "肉視頻",
  description: "獲取 rou.video 視頻",
  author: "alex",
  site: "https://rou.video",
  version: "1.0.0",
  requiredVersion: "0.0.1",
  detailCacheDuration: 60,
  modules: [
    // 最新模块
    {
      title: "最新",
      description: "最新視頻",
      requiresWebView: false,
      functionName: "loadPage",
      sectionMode: false,
      cacheDuration: 3600,
      params: [
        {
          name: "url",
          title: "列表地址",
          type: "constant",
          description: "列表地址",
          value: "https://rou.video/home",
        },
        {
          name: "from",
          title: "頁碼",
          type: "page",
          description: "頁碼",
          value: "1",
        },
      ],
    },
    // 國產AV模块
    {
      title: "國產AV",
      description: "按廠商分類瀏覽國產AV",
      requiresWebView: false,
      functionName: "loadPage",
      sectionMode: false,
      cacheDuration: 3600,
      params: [
        {
          name: "url",
          title: "選擇廠商",
          type: "enumeration",
          description: "選擇廠商",
          value: "https://rou.video/t/糖心Vlog",
          enumOptions: [
            { title: "糖心Vlog", value: "https://rou.video/t/糖心Vlog" },
            { title: "蜜桃影像傳媒", value: "https://rou.video/t/蜜桃影像傳媒" },
            { title: "香蕉視頻傳媒", value: "https://rou.video/t/香蕉視頻傳媒" },
            { title: "星空無限傳媒", value: "https://rou.video/t/星空無限傳媒" },
            { title: "天美傳媒", value: "https://rou.video/t/天美傳媒" },
            { title: "精東影業", value: "https://rou.video/t/精東影業" },
            { title: "91製片廠", value: "https://rou.video/t/91製片廠" },
            { title: "杏吧傳媒", value: "https://rou.video/t/杏吧傳媒" },
            { title: "皇家華人", value: "https://rou.video/t/皇家華人" },
            { title: "起點傳媒", value: "https://rou.video/t/起點傳媒" },
            { title: "大象傳媒", value: "https://rou.video/t/大象傳媒" },
            { title: "果凍傳媒", value: "https://rou.video/t/果凍傳媒" },
            { title: "蘿莉社", value: "https://rou.video/t/蘿莉社" },
            { title: "兔子先生", value: "https://rou.video/t/兔子先生" },
            { title: "扣扣傳媒", value: "https://rou.video/t/扣扣傳媒" },
            { title: "SA國際傳媒", value: "https://rou.video/t/SA國際傳媒" },
            { title: "愛神傳媒", value: "https://rou.video/t/愛神傳媒" },
            { title: "性視界傳媒", value: "https://rou.video/t/性視界傳媒" },
            { title: "抖陰", value: "https://rou.video/t/抖陰" },
            { title: "絕對領域傳媒", value: "https://rou.video/t/絕對領域傳媒" },
            { title: "烏托邦傳媒", value: "https://rou.video/t/烏托邦傳媒" },
            { title: "草莓視頻", value: "https://rou.video/t/草莓視頻" },
            { title: "渡邊傳媒", value: "https://rou.video/t/渡邊傳媒" },
            { title: "樂播傳媒", value: "https://rou.video/t/樂播傳媒" },
            { title: "葫蘆影業", value: "https://rou.video/t/葫蘆影業" },
          ],
        },
        {
          name: "from",
          title: "頁碼",
          type: "page",
          description: "頁碼",
          value: "1",
        },
      ],
    },
    // 麻豆傳媒模块
    {
      title: "麻豆",
      description: "按系列分類瀏覽麻豆傳媒",
      requiresWebView: false,
      functionName: "loadPage",
      sectionMode: false,
      cacheDuration: 3600,
      params: [
        {
          name: "url",
          title: "選擇系列",
          type: "enumeration",
          description: "選擇系列",
          value: "https://rou.video/t/麻豆傳媒",
          enumOptions: [
            { title: "麻豆傳媒（全部）", value: "https://rou.video/t/麻豆傳媒" },
            { title: "愛豆傳媒", value: "https://rou.video/t/愛豆傳媒" },
            { title: "MD", value: "https://rou.video/t/MD" },
            { title: "MDX", value: "https://rou.video/t/MDX" },
            { title: "麻豆US", value: "https://rou.video/t/麻豆US" },
            { title: "MSD", value: "https://rou.video/t/MSD" },
            { title: "MCY", value: "https://rou.video/t/MCY" },
            { title: "MKY", value: "https://rou.video/t/MKY" },
            { title: "MPG", value: "https://rou.video/t/MPG" },
            { title: "FLIXKO", value: "https://rou.video/t/FLIXKO" },
            { title: "貓爪影像", value: "https://rou.video/t/貓爪影像" },
            { title: "麻豆女神微愛視頻", value: "https://rou.video/t/麻豆女神微愛視頻" },
            { title: "麻豆番外", value: "https://rou.video/t/麻豆番外" },
            { title: "麻豆導演系列", value: "https://rou.video/t/麻豆導演系列" },
            { title: "情趣K歌房", value: "https://rou.video/t/情趣K歌房" },
            { title: "突襲女優家", value: "https://rou.video/t/突襲女優家" },
            { title: "國產麻豆AV節目", value: "https://rou.video/t/國產麻豆AV節目" },
          ],
        },
        {
          name: "from",
          title: "頁碼",
          type: "page",
          description: "頁碼",
          value: "1",
        },
      ],
    },
    // 探花模块
    {
      title: "探花",
      description: "按系列分類瀏覽探花",
      requiresWebView: false,
      functionName: "loadPage",
      sectionMode: false,
      cacheDuration: 3600,
      params: [
        {
          name: "url",
          title: "選擇系列",
          type: "enumeration",
          description: "選擇系列",
          value: "https://rou.video/t/探花",
          enumOptions: [
            { title: "探花（全部）", value: "https://rou.video/t/探花" },
            { title: "91沈先生", value: "https://rou.video/t/91沈先生" },
            { title: "探花精選400", value: "https://rou.video/t/探花精選400" },
            { title: "小寶尋花", value: "https://rou.video/t/小寶尋花" },
            { title: "91lisa", value: "https://rou.video/t/91lisa" },
            { title: "午夜尋花", value: "https://rou.video/t/午夜尋花" },
            { title: "91鳳鳴鳥唱", value: "https://rou.video/t/91鳳鳴鳥唱" },
            { title: "大神精選", value: "https://rou.video/t/大神精選" },
            { title: "91貓先生", value: "https://rou.video/t/91貓先生" },
            { title: "千人斬探花", value: "https://rou.video/t/千人斬探花" },
            { title: "全國探花", value: "https://rou.video/t/全國探花" },
            { title: "七天探花", value: "https://rou.video/t/七天探花" },
            { title: "9總全國探花", value: "https://rou.video/t/9總全國探花" },
            { title: "鴨哥探花", value: "https://rou.video/t/鴨哥探花" },
            { title: "錘子探花", value: "https://rou.video/t/錘子探花" },
            { title: "探花合集", value: "https://rou.video/t/探花合集" },
            { title: "李尋歡", value: "https://rou.video/t/李尋歡" },
            { title: "韋小寶", value: "https://rou.video/t/韋小寶" },
            { title: "換妻探花", value: "https://rou.video/t/換妻探花" },
            { title: "行吧傳媒", value: "https://rou.video/t/行吧傳媒" },
          ],
        },
        {
          name: "from",
          title: "頁碼",
          type: "page",
          description: "頁碼",
          value: "1",
        },
      ],
    },
    // 自拍流出模块
    {
      title: "自拍流出",
      description: "自拍流出視頻",
      requiresWebView: false,
      functionName: "loadPage",
      sectionMode: false,
      cacheDuration: 3600,
      params: [
        {
          name: "url",
          title: "列表地址",
          type: "constant",
          description: "列表地址",
          value: "https://rou.video/t/自拍流出",
        },
 
